/*
 * pinchpunch.c
 * Effect      : pinchpunch
 * Strength    : 0.6
 * Generated by: videoeffects
 *
 * CLI equivalent:
 *   ffmpeg -i <input> -vf format=yuv444p16le,scale=ih:ih,"geq='...'",scale=640:360,format=yuv420p <output>
 *
 * Style reference: ffmpeg geq filter (libavfilter/vf_geq.c)
 */

#include <stddef.h>

/* ffmpeg filter string; samples source pixels via p(x,y) */
const char *const vidoeeffects_pinchpunch_vf =
    "format=yuv444p16le,scale=ih:ih,geq='p(W*0.5+(X-W*0.5)*(1-(0.6*0.8)*(1-(3*min(1,hypot(X-W*0.5,Y-H*0.5)/(min(W,H)*0.5))^2-2*min(1,hypot(X-W*0.5,Y-H*0.5)/(min(W,H)*0.5))^3))),H*0.5+(Y-H*0.5)*(1-(0.6*0.8)*(1-(3*min(1,hypot(X-W*0.5,Y-H*0.5)/(min(W,H)*0.5))^2-2*min(1,hypot(X-W*0.5,Y-H*0.5)/(min(W,H)*0.5))^3))))',scale=640:360,format=yuv420p";
